package dev.ftb.mods.ftbic.datagen;

import dev.ftb.mods.ftbic.FTBIC;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class FTBICLanguageProvider extends LanguageProvider {
	public FTBICLanguageProvider(PackOutput output) {
		super(output, FTBIC.MOD_ID, "en_us");
	}

	@Override
	protected void addTranslations() {
		add("itemGroup.ftbic", "FTB Industrial Contraptions");

		add("block.ftbic.active_nuke", "Active Nuke");
		add("block.ftbic.advanced_centrifuge", "Advanced Centrifuge");
		add("block.ftbic.advanced_compressor", "Advanced Compressor");
		add("block.ftbic.advanced_macerator", "Advanced Macerator");
		add("block.ftbic.advanced_machine_block", "Advanced Machine Block");
		add("block.ftbic.advanced_powered_furnace", "Advanced Powered Furnace");
		add("block.ftbic.antimatter_constructor", "Antimatter Constructor");
		add("block.ftbic.basic_generator", "Basic Generator");
		add("block.ftbic.burnt_cable", "Burnt Cable");
		add("block.ftbic.burnt_reinforced_cable", "Burnt Reinforced Cable");
		add("block.ftbic.canning_machine", "Canning Machine");
		add("block.ftbic.centrifuge", "Centrifuge");
		add("block.ftbic.charge_pad", "Charge Pad");
		add("block.ftbic.compressor", "Compressor");
		add("block.ftbic.enderium_block", "Block of Enderium");
		add("block.ftbic.ev_battery_box", "EV Battery Box");
		add("block.ftbic.ev_cable", "EV Cable");
		add("block.ftbic.ev_reinforced_cable", "Reinforced EV Cable");
		add("block.ftbic.ev_rectifier", "EV Energy Rectifier");
		add("block.ftbic.ev_solar_panel", "EV Solar Panel");
		add("block.ftbic.ev_transformer", "EV Transformer");
		add("block.ftbic.exfluid", "Ex-Fluid");
		add("block.ftbic.extruder", "Extruder");
		add("block.ftbic.geothermal_generator", "Geothermal Generator");
		add("block.ftbic.hv_battery_box", "HV Battery Box");
		add("block.ftbic.hv_cable", "HV Cable");
		add("block.ftbic.hv_reinforced_cable", "Reinforced HV Cable");
		add("block.ftbic.hv_rectifier", "HV Energy Rectifier");
		add("block.ftbic.hv_solar_panel", "HV Solar Panel");
		add("block.ftbic.hv_transformer", "HV Transformer");
		add("block.ftbic.iron_furnace", "Iron Furnace");
		add("block.ftbic.iv_cable", "IV Cable");
		add("block.ftbic.iv_reinforced_cable", "Reinforced IV Cable");
		add("block.ftbic.iv_rectifier", "IV Energy Rectifier");
		add("block.ftbic.landmark", "Landmark");
		add("block.ftbic.lv_battery_box", "LV Battery Box");
		add("block.ftbic.lv_cable", "LV Cable");
		add("block.ftbic.lv_reinforced_cable", "Reinforced LV Cable");
		add("block.ftbic.lv_rectifier", "LV Energy Rectifier");
		add("block.ftbic.lv_solar_panel", "LV Solar Panel");
		add("block.ftbic.lv_transformer", "LV Transformer");
		add("block.ftbic.macerator", "Macerator");
		add("block.ftbic.machine_block", "Machine Block");
		add("block.ftbic.mv_battery_box", "MV Battery Box");
		add("block.ftbic.mv_cable", "MV Cable");
		add("block.ftbic.mv_reinforced_cable", "Reinforced MV Cable");
		add("block.ftbic.mv_rectifier", "MV Energy Rectifier");
		add("block.ftbic.mv_solar_panel", "MV Solar Panel");
		add("block.ftbic.mv_transformer", "MV Transformer");
		add("block.ftbic.nuclear_reactor", "Nuclear Reactor");
		add("block.ftbic.nuclear_reactor.broadcast", "%s forgot to cool their Nuclear Reactor!");
		add("block.ftbic.nuclear_reactor_chamber", "Nuclear Reactor Chamber");
		add("block.ftbic.nuke", "Nuke");
		add("block.ftbic.nuke.broadcast", "%s triggered a nuke!");
		add("block.ftbic.powered_crafting_table", "Powered Crafting Table");
		add("block.ftbic.powered_furnace", "Powered Furnace");
		add("block.ftbic.pump", "Pump");
		add("block.ftbic.quarry", "Quarry");
		add("block.ftbic.reinforced_glass", "Reinforced Glass");
		add("block.ftbic.reinforced_stone", "Reinforced Stone");
		add("block.ftbic.reprocessor", "Reprocessor");
		add("block.ftbic.roller", "Roller");
		add("block.ftbic.rubber_sheet", "Rubber Sheet");
		add("block.ftbic.teleporter", "Teleporter");
		add("block.ftbic.teleporter.empty", "No destinations available. Name a peer teleporter and own/publish it.");
		add("block.ftbic.teleporter.load_error", "The destination chunk has to be loaded!");
		add("block.ftbic.teleporter.name_hint", "Teleporter ID");
		add("block.ftbic.teleporter.perm_error", "Only the owner of this teleporter can change its settings!");
		add("block.ftbic.teleporter.pick_header", "Click a destination to link:");
		add("block.ftbic.wind_mill", "Wind Mill");

		add("item.ftbic.active_nuke", "Active Nuke");
		add("item.ftbic.advanced_alloy", "Advanced Alloy");
		add("item.ftbic.advanced_centrifuge", "Advanced Centrifuge");
		add("item.ftbic.advanced_circuit", "Advanced Circuit");
		add("item.ftbic.advanced_compressor", "Advanced Compressor");
		add("item.ftbic.advanced_heat_exchanger", "Advanced Heat Exchanger");
		add("item.ftbic.advanced_heat_vent", "Advanced Heat Vent");
		add("item.ftbic.advanced_macerator", "Advanced Macerator");
		add("item.ftbic.advanced_machine_block", "Advanced Machine Block");
		add("item.ftbic.advanced_powered_furnace", "Advanced Powered Furnace");
		add("item.ftbic.antimatter", "Antimatter");
		add("item.ftbic.antimatter_constructor", "Antimatter Constructor");
		add("item.ftbic.antimatter_crystal", "Antimatter Crystal");
		add("item.ftbic.basic_generator", "Basic Generator");
		add("item.ftbic.burnt_cable", "Burnt Cable");
		add("item.ftbic.burnt_reinforced_cable", "Burnt Reinforced Cable");
		add("item.ftbic.canned_food", "Canned Food");
		add("item.ftbic.canning_machine", "Canning Machine");
		add("item.ftbic.carbon_boots", "Carbon Boots");
		add("item.ftbic.carbon_chestplate", "Carbon Chestplate");
		add("item.ftbic.carbon_fiber_mesh", "Carbon Fiber Mesh");
		add("item.ftbic.carbon_fibers", "Carbon Fibers");
		add("item.ftbic.carbon_helmet", "Carbon Helmet");
		add("item.ftbic.carbon_leggings", "Carbon Leggings");
		add("item.ftbic.carbon_plate", "Carbon Plate");
		add("item.ftbic.centrifuge", "Centrifuge");
		add("item.ftbic.charcoal_dust", "Charcoal Dust");
		add("item.ftbic.charge_pad", "Charge Pad");
		add("item.ftbic.coal_ball", "Coal Ball");
		add("item.ftbic.coal_dust", "Coal Dust");
		add("item.ftbic.component_heat_exchanger", "Component Heat Exchanger");
		add("item.ftbic.component_heat_vent", "Component Heat Vent");
		add("item.ftbic.compressed_coal_ball", "Compressed Coal Ball");
		add("item.ftbic.compressor", "Compressor");
		add("item.ftbic.containment_reactor_plating", "Containment Reactor Plating");
		add("item.ftbic.copper_coil", "Copper Coil");
		add("item.ftbic.creative_battery", "Creative Battery");
		add("item.ftbic.dark_spray_paint_can", "Spray Paint Can (Dark)");
		add("item.ftbic.dense_copper_plate", "Dense Copper Plate");
		add("item.ftbic.diamond_dust", "Diamond Dust");
		add("item.ftbic.dual_uranium_fuel_rod", "Dual Uranium Fuel Rod");
		add("item.ftbic.ejector_upgrade", "Ejector Upgrade");
		add("item.ftbic.electronic_circuit", "Electronic Circuit");
		add("item.ftbic.empty_can", "Empty Can");
		add("item.ftbic.ender_dust", "Ender Dust");
		add("item.ftbic.enderium_block", "Block of Enderium");
		add("item.ftbic.enderium_dust", "Enderium Dust");
		add("item.ftbic.enderium_gear", "Enderium Gear");
		add("item.ftbic.enderium_ingot", "Enderium Ingot");
		add("item.ftbic.enderium_nugget", "Enderium Nugget");
		add("item.ftbic.enderium_plate", "Enderium Plate");
		add("item.ftbic.enderium_rod", "Enderium Rod");
		add("item.ftbic.enderium_wire", "Enderium Wire");
		add("item.ftbic.energy_crystal", "Energy Crystal");
		add("item.ftbic.energy_storage_upgrade", "Energy Storage Upgrade");
		add("item.ftbic.ev_battery", "EV Battery");
		add("item.ftbic.ev_battery_box", "EV Battery Box");
		add("item.ftbic.ev_cable", "EV Cable");
		add("item.ftbic.ev_reinforced_cable", "Reinforced EV Cable");
		add("item.ftbic.ev_rectifier", "EV Energy Rectifier");
		add("item.ftbic.ev_solar_panel", "EV Solar Panel");
		add("item.ftbic.ev_transformer", "EV Transformer");
		add("item.ftbic.exfluid", "Ex-Fluid");
		add("item.ftbic.extruder", "Extruder");
		add("item.ftbic.fluid_cell", "Fluid Cell");
		add("item.ftbic.fluid_cell.contents", "%s / %s mB of %s");
		add("item.ftbic.fluid_cell.empty", "Empty");
		add("item.ftbic.fuse", "Fuse");
		add("item.ftbic.guide", "FTB Industrial Contraptions Guide");
		add("item.ftbic.geothermal_generator", "Geothermal Generator");
		add("item.ftbic.graphene", "Graphene");
		add("item.ftbic.heat_capacity_reactor_plating", "Heat-Capacity Reactor Plating");
		add("item.ftbic.heat_exchanger", "Heat Exchanger");
		add("item.ftbic.heat_vent", "Heat Vent");
		add("item.ftbic.hv_battery", "HV Battery");
		add("item.ftbic.hv_battery_box", "HV Battery Box");
		add("item.ftbic.hv_cable", "HV Cable");
		add("item.ftbic.hv_reinforced_cable", "Reinforced HV Cable");
		add("item.ftbic.hv_rectifier", "HV Energy Rectifier");
		add("item.ftbic.hv_solar_panel", "HV Solar Panel");
		add("item.ftbic.hv_transformer", "HV Transformer");
		add("item.ftbic.industrial_grade_metal", "Industrial Grade Metal");
		add("item.ftbic.iridium_alloy", "Iridium Alloy");
		add("item.ftbic.iridium_circuit", "Iridium Circuit");
		add("item.ftbic.iridium_neutron_reflector", "Iridium Neutron Reflector");
		add("item.ftbic.iron_furnace", "Iron Furnace");
		add("item.ftbic.iv_cable", "IV Cable");
		add("item.ftbic.iv_reinforced_cable", "Reinforced IV Cable");
		add("item.ftbic.iv_rectifier", "IV Energy Rectifier");
		add("item.ftbic.landmark", "Landmark");
		add("item.ftbic.large_coolant_cell", "Large Coolant Cell");
		add("item.ftbic.light_spray_paint_can", "Spray Paint Can (Light)");
		add("item.ftbic.location_card", "Location Card");
		add("item.ftbic.location_card.unbound", "Unbound");
		add("item.ftbic.location_card.unnamed", "Unnamed Teleporter");
		add("item.ftbic.location_card.bound", "Saved destination: %s");
		add("item.ftbic.location_card.linked", "Teleporter linked to %s");
		add("item.ftbic.location_card.cleared", "Location cleared!");
		add("item.ftbic.lv_battery", "LV Battery");
		add("item.ftbic.lv_battery_box", "LV Battery Box");
		add("item.ftbic.lv_cable", "LV Cable");
		add("item.ftbic.lv_reinforced_cable", "Reinforced LV Cable");
		add("item.ftbic.lv_rectifier", "LV Energy Rectifier");
		add("item.ftbic.lv_solar_panel", "LV Solar Panel");
		add("item.ftbic.lv_transformer", "LV Transformer");
		add("item.ftbic.macerator", "Macerator");
		add("item.ftbic.machine_block", "Machine Block");
		add("item.ftbic.mechanical_elytra", "Mechanical Elytra");
		add("item.ftbic.medium_coolant_cell", "Medium Coolant Cell");
		add("item.ftbic.mixed_metal_blend", "Mixed Metal Blend");
		add("item.ftbic.mv_battery", "MV Battery");
		add("item.ftbic.mv_battery_box", "MV Battery Box");
		add("item.ftbic.mv_cable", "MV Cable");
		add("item.ftbic.mv_reinforced_cable", "Reinforced MV Cable");
		add("item.ftbic.mv_rectifier", "MV Energy Rectifier");
		add("item.ftbic.mv_solar_panel", "MV Solar Panel");
		add("item.ftbic.mv_transformer", "MV Transformer");
		add("item.ftbic.neutron_reflector", "Neutron Reflector");
		add("item.ftbic.nuclear_reactor", "Nuclear Reactor");
		add("item.ftbic.nuclear_reactor_chamber", "Nuclear Reactor Chamber");
		add("item.ftbic.nuke", "Nuke");
		add("item.ftbic.nuke_arrow", "Nuke Arrow");
		add("item.ftbic.obsidian_dust", "Obsidian Dust");
		add("item.ftbic.overclocked_heat_vent", "Overclocked Heat Vent");
		add("item.ftbic.overclocker_upgrade", "Overclocker Upgrade");
		add("item.ftbic.powered_crafting_table", "Powered Crafting Table");
		add("item.ftbic.powered_furnace", "Powered Furnace");
		add("item.ftbic.protein_bar", "Feed The Beast\u00e2\u201e\u00a2 Protein Bar");
		add("item.ftbic.pump", "Pump");
		add("item.ftbic.quad_uranium_fuel_rod", "Quad Uranium Fuel Rod");
		add("item.ftbic.quantum_boots", "Quantum Boots");
		add("item.ftbic.quantum_chestplate", "Quantum Chestplate");
		add("item.ftbic.quantum_helmet", "Quantum Helmet");
		add("item.ftbic.quantum_leggings", "Quantum Leggings");
		add("item.ftbic.quarry", "Quarry");
		add("item.ftbic.reactor_heat_exchanger", "Reactor Heat Exchanger");
		add("item.ftbic.reactor_heat_vent", "Reactor Heat Vent");
		add("item.ftbic.reactor_plating", "Reactor Plating");
		add("item.ftbic.reinforced_glass", "Reinforced Glass");
		add("item.ftbic.reinforced_stone", "Reinforced Stone");
		add("item.ftbic.reprocessor", "Reprocessor");
		add("item.ftbic.roller", "Roller");
		add("item.ftbic.rubber", "Rubber");
		add("item.ftbic.rubber_sheet", "Rubber Sheet");
		add("item.ftbic.scrap", "Scrap");
		add("item.ftbic.scrap_box", "Scrap Box");
		add("item.ftbic.single_use_battery", "Single Use Battery");
		add("item.ftbic.small_coolant_cell", "Small Coolant Cell");
		add("item.ftbic.spray_paint_can.tooltip", "Right-click on a machine to change its theme");
		add("item.ftbic.teleporter", "Teleporter");
		add("item.ftbic.thick_neutron_reflector", "Thick Neutron Reflector");
		add("item.ftbic.tooltip.creative_energy", "Infinite Energy");
		add("item.ftbic.tooltip.energy", "%s / %s zaps");
		add("item.ftbic.tooltip.tier", "Tier: %s");
		add("item.ftbic.transformer_upgrade", "Transformer Upgrade");
		add("item.ftbic.uranium_fuel_rod", "Uranium Fuel Rod");
		add("item.ftbic.wind_mill", "Wind Mill");

		add("recipe.ftbic.canning", "Canning");
		add("recipe.ftbic.compressing", "Compressing");
		add("recipe.ftbic.extruding", "Extruding");
		add("recipe.ftbic.macerating", "Macerating");
		add("recipe.ftbic.reconstructing", "Reconstructing");
		add("recipe.ftbic.reprocessing", "Reprocessing");
		add("recipe.ftbic.rolling", "Rolling");
		add("recipe.ftbic.separating", "Separating");

		add("ftbic.any_item", "Any Item");
		add("ftbic.energy_capacity", "Capacity: %s");
		add("ftbic.energy_output", "Output: %s");
		add("ftbic.energy_usage", "Usage: %s");
		add("ftbic.fuse_info", "Right-click with a fuse to repair burnt machines.");
		add("ftbic.max_input", "Max Input: %s");
		add("ftbic.requires_chestplate", "Requires Chestplate to function");
		add("ftbic.zap_to_fe_conversion", "%s = %s FE");

		add("ftbic.jade.burnt", "\u00c2\u00a7cBurnt");
		add("ftbic.jade.cable_tier", "Tier: %s");
		add("ftbic.jade.fluid", "Fluid: %s / %s mB");
		add("ftbic.jade.fluid_empty", "Tank: Empty");
		add("ftbic.jade.lava", "Lava: %s / %s mB");
		add("ftbic.jade.progress", "Progress: %s%%");
		add("ftbic.jade.reactor_heat", "Heat: %s%%");
		add("ftbic.jade.reactor_output", "Output: %s/t");
		add("ftbic.jade.reactor_paused", "Paused (%s/t when active)");
		add("ftbic.jade.water", "Water: %s / %s mB");

		add("config.jade.plugin_ftbic.cable_tier", "Cable Tier");
		add("config.jade.plugin_ftbic.energy", "Energy");
	}
}
