package dev.ftb.mods.industrialcontraptions.datagen;

import dev.ftb.mods.industrialcontraptions.IC;
import dev.ftb.mods.industrialcontraptions.material.MaterialEntries;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ICLanguageProvider extends LanguageProvider {
	public ICLanguageProvider(PackOutput output) {
		super(output, IC.MOD_ID, "en_us");
	}

	@Override
	protected void addTranslations() {
		MaterialEntries.all().forEach(entry -> {
			String text = entry.component().translation(entry.material().displayName());
			String suffix = IC.MOD_ID + "." + entry.name();
			if (entry.component().isBlock()) {
				add("block." + suffix, text);
				add("item." + suffix, text);
			} else {
				add("item." + suffix, text);
			}
		});

		add("itemGroup.ic", "Industrial Contraptions");

		add("block.ic.active_nuke", "Active Nuke");
		add("block.ic.advanced_centrifuge", "Advanced Centrifuge");
		add("block.ic.advanced_compressor", "Advanced Compressor");
		add("block.ic.advanced_macerator", "Advanced Macerator");
		add("block.ic.advanced_machine_block", "Advanced Machine Block");
		add("block.ic.advanced_powered_furnace", "Advanced Powered Furnace");
		add("block.ic.alloy_smelter", "Alloy Smelter");
		add("block.ic.antimatter_constructor", "Antimatter Constructor");
		add("block.ic.basic_generator", "Basic Generator");
		add("block.ic.burnt_cable", "Burnt Cable");
		add("block.ic.burnt_reinforced_cable", "Burnt Reinforced Cable");
		add("block.ic.canning_machine", "Canning Machine");
		add("block.ic.centrifuge", "Centrifuge");
		add("block.ic.charge_pad", "Charge Pad");
		add("block.ic.compressor", "Compressor");
		add("block.ic.enderium_block", "Block of Enderium");
		add("block.ic.ev_battery_box", "EV Battery Box");
		add("block.ic.ev_cable", "EV Cable");
		add("block.ic.ev_reinforced_cable", "Reinforced EV Cable");
		add("block.ic.ev_rectifier", "EV Energy Rectifier");
		add("block.ic.ev_solar_panel", "EV Solar Panel");
		add("block.ic.ev_transformer", "EV Transformer");
		add("block.ic.exfluid", "Ex-Fluid");
		add("block.ic.extruder", "Extruder");
		add("block.ic.geothermal_generator", "Geothermal Generator");
		add("block.ic.hv_battery_box", "HV Battery Box");
		add("block.ic.hv_cable", "HV Cable");
		add("block.ic.hv_reinforced_cable", "Reinforced HV Cable");
		add("block.ic.hv_rectifier", "HV Energy Rectifier");
		add("block.ic.hv_solar_panel", "HV Solar Panel");
		add("block.ic.hv_transformer", "HV Transformer");
		add("block.ic.iron_furnace", "Iron Furnace");
		add("block.ic.iv_cable", "IV Cable");
		add("block.ic.iv_reinforced_cable", "Reinforced IV Cable");
		add("block.ic.iv_rectifier", "IV Energy Rectifier");
		add("block.ic.landmark", "Landmark");
		add("block.ic.lv_battery_box", "LV Battery Box");
		add("block.ic.lv_cable", "LV Cable");
		add("block.ic.lv_reinforced_cable", "Reinforced LV Cable");
		add("block.ic.lv_rectifier", "LV Energy Rectifier");
		add("block.ic.lv_solar_panel", "LV Solar Panel");
		add("block.ic.lv_transformer", "LV Transformer");
		add("block.ic.macerator", "Macerator");
		add("block.ic.machine_block", "Machine Block");
		add("block.ic.mv_battery_box", "MV Battery Box");
		add("block.ic.mv_cable", "MV Cable");
		add("block.ic.mv_reinforced_cable", "Reinforced MV Cable");
		add("block.ic.mv_rectifier", "MV Energy Rectifier");
		add("block.ic.mv_solar_panel", "MV Solar Panel");
		add("block.ic.mv_transformer", "MV Transformer");
		add("block.ic.nuclear_reactor", "Nuclear Reactor");
		add("block.ic.nuclear_reactor.broadcast", "%s forgot to cool their Nuclear Reactor!");
		add("block.ic.nuclear_reactor_chamber", "Nuclear Reactor Chamber");
		add("block.ic.nuke", "Nuke");
		add("block.ic.nuke.broadcast", "%s triggered a nuke!");
		add("block.ic.powered_crafting_table", "Powered Crafting Table");
		add("block.ic.powered_furnace", "Powered Furnace");
		add("block.ic.pump", "Pump");
		add("block.ic.quarry", "Quarry");
		add("block.ic.reactor_simulator", "Reactor Simulator");
		add("block.ic.reinforced_glass", "Reinforced Glass");
		add("block.ic.reinforced_stone", "Reinforced Stone");
		add("block.ic.reprocessor", "Reprocessor");
		add("block.ic.roller", "Roller");
		add("block.ic.rubber_sheet", "Rubber Sheet");
		add("block.ic.teleporter", "Teleporter");
		add("block.ic.teleporter.empty", "No destinations available. Name a peer teleporter and own/publish it.");
		add("block.ic.teleporter.load_error", "The destination chunk has to be loaded!");
		add("block.ic.teleporter.name_hint", "Teleporter ID");
		add("block.ic.teleporter.perm_error", "Only the owner of this teleporter can change its settings!");
		add("block.ic.teleporter.pick_header", "Click a destination to link:");
		add("block.ic.wind_mill", "Wind Mill");

		add("item.ic.active_nuke", "Active Nuke");
		add("item.ic.advanced_alloy", "Advanced Alloy");
		add("item.ic.advanced_centrifuge", "Advanced Centrifuge");
		add("item.ic.advanced_circuit", "Advanced Circuit");
		add("item.ic.advanced_compressor", "Advanced Compressor");
		add("item.ic.advanced_heat_exchanger", "Advanced Heat Exchanger");
		add("item.ic.advanced_heat_vent", "Advanced Heat Vent");
		add("item.ic.advanced_macerator", "Advanced Macerator");
		add("item.ic.advanced_machine_block", "Advanced Machine Block");
		add("item.ic.advanced_powered_furnace", "Advanced Powered Furnace");
		add("item.ic.alloy_smelter", "Alloy Smelter");
		add("item.ic.antimatter", "Antimatter");
		add("item.ic.antimatter_constructor", "Antimatter Constructor");
		add("item.ic.antimatter_crystal", "Antimatter Crystal");
		add("item.ic.basic_generator", "Basic Generator");
		add("item.ic.burnt_cable", "Burnt Cable");
		add("item.ic.burnt_reinforced_cable", "Burnt Reinforced Cable");
		add("item.ic.canned_food", "Canned Food");
		add("item.ic.canning_machine", "Canning Machine");
		add("item.ic.carbon_boots", "Carbon Boots");
		add("item.ic.carbon_chestplate", "Carbon Chestplate");
		add("item.ic.carbon_fiber_mesh", "Carbon Fiber Mesh");
		add("item.ic.carbon_fibers", "Carbon Fibers");
		add("item.ic.carbon_helmet", "Carbon Helmet");
		add("item.ic.carbon_leggings", "Carbon Leggings");
		add("item.ic.carbon_plate", "Carbon Plate");
		add("item.ic.centrifuge", "Centrifuge");
		add("item.ic.charge_pad", "Charge Pad");
		add("item.ic.coal_ball", "Coal Ball");
		add("item.ic.component_heat_exchanger", "Component Heat Exchanger");
		add("item.ic.component_heat_vent", "Component Heat Vent");
		add("item.ic.compressed_coal_ball", "Compressed Coal Ball");
		add("item.ic.compressor", "Compressor");
		add("item.ic.containment_reactor_plating", "Containment Reactor Plating");
		add("item.ic.copper_coil", "Copper Coil");
		add("item.ic.creative_battery", "Creative Battery");
		add("item.ic.dark_spray_paint_can", "Spray Paint Can (Dark)");
		add("item.ic.dense_copper_plate", "Dense Copper Plate");
		add("item.ic.dual_uranium_fuel_rod", "Dual Uranium Fuel Rod");
		add("item.ic.ejector_upgrade", "Ejector Upgrade");
		add("item.ic.electronic_circuit", "Electronic Circuit");
		add("item.ic.empty_can", "Empty Can");
		add("item.ic.enderium_block", "Block of Enderium");
		add("item.ic.enderium_dust", "Enderium Dust");
		add("item.ic.enderium_gear", "Enderium Gear");
		add("item.ic.enderium_ingot", "Enderium Ingot");
		add("item.ic.enderium_nugget", "Enderium Nugget");
		add("item.ic.enderium_plate", "Enderium Plate");
		add("item.ic.enderium_rod", "Enderium Rod");
		add("item.ic.enderium_wire", "Enderium Wire");
		add("item.ic.energy_crystal", "Energy Crystal");
		add("item.ic.energy_storage_upgrade", "Energy Storage Upgrade");
		add("item.ic.ev_battery", "EV Battery");
		add("item.ic.ev_battery_box", "EV Battery Box");
		add("item.ic.ev_cable", "EV Cable");
		add("item.ic.ev_reinforced_cable", "Reinforced EV Cable");
		add("item.ic.ev_rectifier", "EV Energy Rectifier");
		add("item.ic.ev_solar_panel", "EV Solar Panel");
		add("item.ic.ev_transformer", "EV Transformer");
		add("item.ic.exfluid", "Ex-Fluid");
		add("item.ic.extruder", "Extruder");
		add("item.ic.fluid_cell", "Fluid Cell");
		add("item.ic.fluid_cell.contents", "%s / %s mB of %s");
		add("item.ic.fluid_cell.empty", "Empty");
		add("item.ic.fuse", "Fuse");
		add("item.ic.guide", "Industrial Contraptions Guide");
		add("item.ic.geothermal_generator", "Geothermal Generator");
		add("item.ic.graphene", "Graphene");
		add("item.ic.heat_capacity_reactor_plating", "Heat-Capacity Reactor Plating");
		add("item.ic.heat_exchanger", "Heat Exchanger");
		add("item.ic.heat_vent", "Heat Vent");
		add("item.ic.hv_battery", "HV Battery");
		add("item.ic.hv_battery_box", "HV Battery Box");
		add("item.ic.hv_cable", "HV Cable");
		add("item.ic.hv_reinforced_cable", "Reinforced HV Cable");
		add("item.ic.hv_rectifier", "HV Energy Rectifier");
		add("item.ic.hv_solar_panel", "HV Solar Panel");
		add("item.ic.hv_transformer", "HV Transformer");
		add("item.ic.industrial_grade_metal", "Industrial Grade Metal");
		add("item.ic.iridium_alloy", "Iridium Alloy");
		add("item.ic.iridium_circuit", "Iridium Circuit");
		add("item.ic.iridium_neutron_reflector", "Iridium Neutron Reflector");
		add("item.ic.iron_furnace", "Iron Furnace");
		add("item.ic.iv_cable", "IV Cable");
		add("item.ic.iv_reinforced_cable", "Reinforced IV Cable");
		add("item.ic.iv_rectifier", "IV Energy Rectifier");
		add("item.ic.landmark", "Landmark");
		add("item.ic.large_coolant_cell", "Large Coolant Cell");
		add("item.ic.light_spray_paint_can", "Spray Paint Can (Light)");
		add("item.ic.location_card", "Location Card");
		add("item.ic.location_card.unbound", "Unbound");
		add("item.ic.location_card.unnamed", "Unnamed Teleporter");
		add("item.ic.location_card.bound", "Saved destination: %s");
		add("item.ic.location_card.linked", "Teleporter linked to %s");
		add("item.ic.location_card.cleared", "Location cleared!");
		add("item.ic.lv_battery", "LV Battery");
		add("item.ic.lv_battery_box", "LV Battery Box");
		add("item.ic.lv_cable", "LV Cable");
		add("item.ic.lv_reinforced_cable", "Reinforced LV Cable");
		add("item.ic.lv_rectifier", "LV Energy Rectifier");
		add("item.ic.lv_solar_panel", "LV Solar Panel");
		add("item.ic.lv_transformer", "LV Transformer");
		add("item.ic.macerator", "Macerator");
		add("item.ic.machine_block", "Machine Block");
		add("item.ic.mechanical_elytra", "Mechanical Elytra");
		add("item.ic.medium_coolant_cell", "Medium Coolant Cell");
		add("item.ic.mixed_metal_blend", "Mixed Metal Blend");
		add("item.ic.mv_battery", "MV Battery");
		add("item.ic.mv_battery_box", "MV Battery Box");
		add("item.ic.mv_cable", "MV Cable");
		add("item.ic.mv_reinforced_cable", "Reinforced MV Cable");
		add("item.ic.mv_rectifier", "MV Energy Rectifier");
		add("item.ic.mv_solar_panel", "MV Solar Panel");
		add("item.ic.mv_transformer", "MV Transformer");
		add("item.ic.neutron_reflector", "Neutron Reflector");
		add("item.ic.nuclear_reactor", "Nuclear Reactor");
		add("item.ic.nuclear_reactor_chamber", "Nuclear Reactor Chamber");
		add("item.ic.nuke", "Nuke");
		add("item.ic.nuke_arrow", "Nuke Arrow");
		add("item.ic.overclocked_heat_vent", "Overclocked Heat Vent");
		add("item.ic.overclocker_upgrade", "Overclocker Upgrade");
		add("item.ic.powered_crafting_table", "Powered Crafting Table");
		add("item.ic.powered_furnace", "Powered Furnace");
		add("item.ic.protein_bar", "Feed The Beast\u00e2\u201e\u00a2 Protein Bar");
		add("item.ic.pump", "Pump");
		add("item.ic.quad_uranium_fuel_rod", "Quad Uranium Fuel Rod");
		add("item.ic.quantum_boots", "Quantum Boots");
		add("item.ic.quantum_chestplate", "Quantum Chestplate");
		add("item.ic.quantum_helmet", "Quantum Helmet");
		add("item.ic.quantum_leggings", "Quantum Leggings");
		add("item.ic.quarry", "Quarry");
		add("item.ic.reactor_heat_exchanger", "Reactor Heat Exchanger");
		add("item.ic.reactor_heat_vent", "Reactor Heat Vent");
		add("item.ic.reactor_plating", "Reactor Plating");
		add("item.ic.reactor_simulator", "Reactor Simulator");
		add("item.ic.reinforced_glass", "Reinforced Glass");
		add("item.ic.reinforced_stone", "Reinforced Stone");
		add("item.ic.reprocessor", "Reprocessor");
		add("item.ic.roller", "Roller");
		add("item.ic.rubber", "Rubber");
		add("item.ic.rubber_sheet", "Rubber Sheet");
		add("item.ic.sticky_resin", "Sticky Resin");
		add("item.ic.latex_ball", "Latex Ball");
		add("item.ic.scrap", "Scrap");
		add("item.ic.scrap_box", "Scrap Box");
		add("item.ic.single_use_battery", "Single Use Battery");
		add("item.ic.small_coolant_cell", "Small Coolant Cell");
		add("item.ic.spray_paint_can.tooltip", "Right-click on a machine to change its theme");
		add("item.ic.teleporter", "Teleporter");
		add("item.ic.thick_neutron_reflector", "Thick Neutron Reflector");
		add("item.ic.tooltip.creative_energy", "Infinite Energy");
		add("item.ic.tooltip.energy", "%s / %s zaps");
		add("item.ic.tooltip.tier", "Tier: %s");
		add("item.ic.transformer_upgrade", "Transformer Upgrade");
		add("item.ic.uranium_fuel_rod", "Uranium Fuel Rod");
		add("item.ic.wind_mill", "Wind Mill");

		add("recipe.ic.alloy_smelting", "Alloy Smelting");
		add("recipe.ic.canning", "Canning");
		add("recipe.ic.compressing", "Compressing");
		add("recipe.ic.extruding", "Extruding");
		add("recipe.ic.macerating", "Macerating");
		add("recipe.ic.reconstructing", "Reconstructing");
		add("recipe.ic.reprocessing", "Reprocessing");
		add("recipe.ic.rolling", "Rolling");
		add("recipe.ic.separating", "Separating");

		add("ic.any_item", "Any Item");
		add("ic.energy_capacity", "Capacity: %s");
		add("ic.energy_output", "Output: %s");
		add("ic.energy_usage", "Usage: %s");
		add("ic.fuse_info", "Right-click with a fuse to repair burnt machines.");
		add("ic.max_input", "Max Input: %s");
		add("ic.requires_chestplate", "Requires Chestplate to function");
		add("ic.zap_to_fe_conversion", "%s = %s FE");

		add("ic.jade.burnt", "\u00c2\u00a7cBurnt");
		add("ic.jade.cable_tier", "Tier: %s");
		add("ic.jade.fluid", "Fluid: %s / %s mB");
		add("ic.jade.fluid_empty", "Tank: Empty");
		add("ic.jade.lava", "Lava: %s / %s mB");
		add("ic.jade.progress", "Progress: %s%%");
		add("ic.jade.starving", "Starving for power");
		add("ic.jade.reactor_heat", "Heat: %s%%");
		add("ic.jade.reactor_output", "Output: %s/t");
		add("ic.jade.reactor_paused", "Paused (%s/t when active)");
		add("ic.jade.water", "Water: %s / %s mB");
		add("ic.jade.tele_power", "Power: HV (shared with linked pair)");
		add("ic.jade.tele_send_items", "Sending: %s items");
		add("ic.jade.tele_receive_items", "Received: %s items");
		add("ic.jade.tele_send_fluid", "Sending %s: %s / %s mB");
		add("ic.jade.tele_send_fluid_empty", "Send tank: Empty (0 / %s mB)");
		add("ic.jade.tele_receive_fluid", "Received %s: %s / %s mB");
		add("ic.jade.tele_receive_fluid_empty", "Receive tank: Empty (0 / %s mB)");

		add("config.jade.plugin_ic.cable_tier", "Cable Tier");
		add("config.jade.plugin_ic.energy", "Energy");
	}
}
